version: '3.8'

services:
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blogphp
    networks:
      - blogphp

  php:
    depends_on:
      - db
    image: php:8.0-apache
    ports:
      - "80:80"
    volumes:
      - ./web:/var/www/html/
    networks:
      - blogphp

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    ports:
      - "8081:80"
    restart: always
    environment:
      PMA_host: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - blogphp

networks:
  blogphp:
volumes:
  db_data: