version: '3.8'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blogphp
    networks:
      - blogphp

  php:
    depends_on:
      - db
      - maildev
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/
    networks:
      - blogphp
    user: 1000:1000

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    ports:
      - "8081:80"
    restart: always
    environment:
      PMA_host: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - blogphp

  maildev:
    image: maildev/maildev
    ports:
      - "1080:80"
    networks:
      - blogphp

networks:
  blogphp:
volumes:
  db_data: