<?php

namespace App\Model;

use App\Core\Text;
use App\Repository\CategoryRepository;

class Post extends MainModel
{
    private const TABLE_NAME = "post";

    private $id;
    private $title;
    private $image;
    private $lead;
    private $excerpt;
    private $content;
    private $author;
    private $authorId;
    private $categoryId;
    private $slug;
    private $last_update;


    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    public function setTitle($title)
    {
        $this->title = $title;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getTitle()
    {
        return $this->title;
    }

    public function setImage($image)
    {
        if (is_array($image) && !empty($image)) {
            $this->image = $image;
        }
        return $this;
    }

    public function getImage()
    {
        return $this->image;
    }

    public function setLead($lead)
    {
        $this->lead = $lead;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getLead()
    {
        return $this->lead;
    }

    /**
     * @return mixed
     */
    public function getExcerpt()
    {
        if ($this->lead === null) {
            return null;
        }
        return Text::excerpt($this->lead, 60);
    }

    public function setContent($content)
    {
        $this->content = $content;
        return $this;
    }

    public function getContent()
    {
        return $this->content;
    }

    public function setAuthorId($authorId)
    {
        $this->author_id = $authorId;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getAutorId()
    {
        return $this->authorId;
    }

    public function setCategoryId($category_id)
    {
        $this->categoryId = $category_id;
        return $this;
    }

    /**
     * @return array
     */
    public function getCategoryId()
    {
        return $this->categoryId;
    }

    // ERREUR NE RECUPERE PAS LE PDO lors de l'instance getDatabase
    public function getCategory()
    {
        return CategoryRepository::findById($this->categoryId);
    }

    public function setSlug($slug)
    {
        $this->slug = $slug;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getSlug()
    {
        return $this->slug;
    }

    public function setLastUpdate()
    {
        $this->last_update = date('d-F-Y');
        return $this;
    }


    /**
     * @return mixed
     */
    public function getLastUpdate(): \DateTime
    {
        return new \DateTime($this->last_update);
    }

    public function add()
    {
        $this->query(
            'INSERT INTO post(
                 title, lead, author_id, category_id, slug, content)
                 VALUES(:title, :lead, :author_id, :category_id, :slug, :content)',
            [
                'title' => $this->title,
                'lead' => $this->lead,
                'author_id' => $this->authorId,
                'category_id' => $this->categoryId,
                'slug' => $this->slug,
                'content' => $this->content
            ]
        );
    }

    public function edit()
    {
        // TODO
    }

    public function delete($request, $params = false)
    {
        return parent::delete($request, $params); // TODO: Change the autogenerated stub
    }

    public static function getTableName()
    {
        return self::TABLE_NAME;
    }
}
